/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEColorSwitchInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEncryptedScore"
      | "lastScore"
      | "protocolId"
      | "totalScores"
      | "viewEncryptedScores"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addEncryptedScore",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalScores",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "viewEncryptedScores",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEncryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewEncryptedScores",
    data: BytesLike
  ): Result;
}

export interface FHEColorSwitch extends BaseContract {
  connect(runner?: ContractRunner | null): FHEColorSwitch;
  waitForDeployment(): Promise<this>;

  interface: FHEColorSwitchInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEncryptedScore: TypedContractMethod<
    [cipherScore: BytesLike, validationProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lastScore: TypedContractMethod<[user: AddressLike], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  totalScores: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  viewEncryptedScores: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEncryptedScore"
  ): TypedContractMethod<
    [cipherScore: BytesLike, validationProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastScore"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalScores"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "viewEncryptedScores"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;

  filters: {};
}
